### ISSUE TITLE
Remove ns0.ldn-fai.net from the jenkins (and from stubby configuration)

### ISSUE THREAD

**Issue by Schplaf** [dnsprivacy/dnsprivacy.org_issues#2]
Hello,

I am a member of LDN (the non-profit organization which runs ns0.ldn-fai.net). Due to lack of manpower, we are stopping our activity. The server is unmaintained (all red on the Jenkins :\) and will be stopped in a near future. To avoid more people to use it, is it possible to remove it from your monitoring and from the default stubby configuration?

Thank you,

s., for LDN

**Comment by Sami32** [comment]
I was sad to discover that you shutted down :-(

As an alternative the following "brother" one could be added:
https://www.fdn.fr/actions/dns/

**Comment by saradickinson** [comment]
LDN server removed some time ago - but issue left open! Many thanks for running the server while you did!

`fdn.fr` server added to `Test Servers` page and monitoring
