### ISSUE TITLE
Suggest adding Wikimedia DNS to the Public Resolvers page

### ISSUE THREAD

**Issue by arthuredelstein** [dnsprivacy/dnsprivacy.org_issues#7]
[Wikimedia DNS](https://meta.wikimedia.org/wiki/Wikimedia_DNS) offers a public, open-source, anycasted DoH and DoT resolver offering strong privacy (no logging). More technical details at https://wikitech.wikimedia.org/wiki/Wikimedia_DNS

**Comment by saradickinson** [comment]
Thanks - (belatedly) done!

**Comment by arthuredelstein** [comment]
Thank you Sara!

**Comment by arthuredelstein** [comment]
One observation -- the Wikimedia row in the DNS-over-HTTPS (DoH) table looks misformatted to me.

**Comment by saradickinson** [comment]
Oof - copy paste error. Fixed now - thanks!

**Comment by arthuredelstein** [comment]
Thanks Sara!
